[connections.snowflake]
account = "streamlitcommunitycloud-admin_gcp"
user = "UNRUFFLED_MONTALCINI_8029256820892073177"
role = "READONLY_ROLE_8029256820892073177"
warehouse = "COMPUTE_WH_8029256820892073177"
private_key_file = "./.streamlit/dataset-credentials.p8"